on:
    jobs:
      my_job:
        runs-on: ubuntu-latest
        steps:
          - name: Write secret to file
            run: |
              echo "${{ secrets.MY_SECRET_KEY}}" > secret.txt
            env:
              MY_SECRET_KEY: ${{ secrets.OSINT_API_1 }}
